//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanLinhKien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public int maKH { get; set; }
        public string tenKH { get; set; }
        public string diaChi { get; set; }
        public string soDienThoai { get; set; }
        public string taiKhoan { get; set; }
        public string matKhau { get; set; }
        public string Email { get; set; }
    }
}
